<?xml version="1.0" ?>
<robot name = "hexa_leg_pod" xmlns:xacro = "http://www.ros.org/wiki/xacro">
    <!-- include -->
    <xacro:include filename="$(find multileg)/urdf/materials.xacro" />

    <!--Setting property-->
    <xacro:property name="motor_height" value="0.02" /> <!--motorを下げる高さ[m]-->
    <xacro:property name="cylinder_radius" value="0.095" /> <!--bodyの半径[m]-->

    <!-- 脚設定マクロ-->
    <xacro:macro name="limb_macro" params="limb_id arc">
        <!-- モーターの設定 -->
        <link name ="motor${limb_id}">
            <!--  物理シミュレーションのための質量特性を定義 -->
            <inertial>
                <!-- 慣性フレームの位置と向き -->
                <origin xyz ="0 0 0" rpy ="0 0 0"/>
                <!-- 部品の質量（kg単位） -->
                <mass  value = "0.125"/>
                <!--  慣性テンソル（物体の回転に対する抵抗を定義する行列） -->
                <!-- ixx, iyy, izz - 各軸周りの慣性モーメント -->
                <!-- ixy, iyz, ixz - 慣性乗積（オフ対角成分） -->
                <inertia ixx ="0.1" iyy ="0.1" izz ="0.1" ixy ="0.0" iyz ="0.0" ixz = "0.0"/>
            </inertial>

            <!-- 視覚・表示の設定 -->
            <visual>
                <!-- 表示モデルの位置と向き -->
                <origin xyz ="0 0.005 0" rpy ="0 0 0"/>
                <!--  形状を定義 -->
                <geometry>
                    <mesh filename ="package://dual_leg_controller/model/meshes/motor.stl" scale ="0.001 0.001 0.001"/>
                </geometry>
                <material name ="steel_satin"/>
            </visual>

            <!-- 衝突検出形状 (物理シミュレーション用)の設定 -->
            <collision>
                <!-- 衝突モデルの位置と向き -->
                <origin xyz="0 0.005 0" rpy="0 0 0"/>
                <!--  形状を定義 -->
                <geometry>
                    <mesh filename="package://dual_leg_controller/model/meshes/motor.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>

        <!-- coxa_motor と femur_motor をつなぐリンク(leg_coxa)の定義  -->
        <link name="limb${limb_id}_link2">
            <!--  物理シミュレーションのための質量特性を定義 -->
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.125"/>
                <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0.0" iyz="0.0" ixz="0.0"/>
            </inertial>

            <!-- 視覚・表示の設定 -->
            <visual>
                <origin xyz="0 0 -0.045" rpy="0 ${radians(-90)} 0"/>
                <geometry>
                    <mesh filename="package://dual_leg_controller/model/meshes/link1_1.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="steel_satin"/>
            </visual>

            <!-- 衝突検出形状 (物理シミュレーション用)の設定 -->
            <collision>
                <origin xyz="0 0 -0.045" rpy="0 ${radians(-90)} 0"/>
                <geometry>
                    <mesh filename="package://dual_leg_controller/model/meshes/link1_1.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>

        <!-- femur_motor と tibia_motor をつなぐリンク(leg_fumer)の定義  -->
         <link name="limb${limb_id}_link4">
            <inertial>
                <mass value="0.125"/>
                <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0.0" iyz="0.0" ixz="0.0"/>
            </inertial>
            <visual>
                <origin xyz="0.05 -0.055 0" rpy="0 ${radians(180)} ${radians(-90)}"/>
                <geometry>
                    <mesh filename="package://dual_leg_controller/model/meshes/link2_1.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="steel_satin"/>
            </visual>
            <collision>
                <origin xyz="0.05 -0.055 0" rpy="0 ${radians(180)} ${radians(-90)}"/>
                <geometry>
                    <mesh filename="package://dual_leg_controller/model/meshes/link2_1.stl" scale="0.001 0.001 0.001"/>
                </geometry>
            </collision>
        </link>
        
        <link name="limb${limb_id}_link6">
            <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="0.125"/>
            <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0.0" iyz="0.0" ixz="0.0"/>
            </inertial>
            <visual>
            <origin xyz="0.055 0.038 0" rpy="${radians(180)} 0 ${radians(180)}"/>
            <geometry>
                <mesh filename="package://dual_leg_controller/model/meshes/link3_1.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            <material name="steel_satin"/>
            </visual>
            <collision>
            <origin xyz="0.055 0.038 0" rpy="${radians(180)} 0 ${radians(180)}"/>
            <geometry>
                <mesh filename="package://dual_leg_controller/model/meshes/link3_1.stl" scale="0.001 0.001 0.001"/>
            </geometry>
            </collision>
            <!-- 座標系確認用の軸表示を追加 -->
            <visual name="debug_x_axis">
                <origin xyz="0.02 0 0" rpy="0 ${radians(90)} 0"/>
                <geometry>
                    <cylinder radius="0.002" length="0.04"/>
                </geometry>
                <material name="debug_red">
                    <color rgba="1.0 0.0 0.0 1.0"/>
                </material>
            </visual>
            
            <visual name="debug_y_axis">
                <origin xyz="0 0.02 0" rpy="${radians(90)} 0 0"/>
                <geometry>
                    <cylinder radius="0.002" length="0.04"/>
                </geometry>
                <material name="debug_green">
                    <color rgba="0.0 1.0 0.0 1.0"/>
                </material>
            </visual>
            
            <visual name="debug_z_axis">
                <origin xyz="0 0 0.02" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="0.002" length="0.04"/>
                </geometry>
                <material name="debug_blue">
                    <color rgba="0.0 0.0 1.0 1.0"/>
                </material>
            </visual>
        </link>

        <!-- 脚先（foot_tip）を示す非常に小さなリンク -->
        <link name="limb${limb_id}_foot_tip">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.0001"/>
                <inertia ixx="0.00001" iyy="0.00001" izz="0.00001" ixy="0.0" iyz="0.0" ixz="0.0"/>
            </inertial>
            
            <!-- X軸（前方向）- 赤色 -->
            <visual name="x_axis">
                <origin xyz="0.01 0 0" rpy="0 ${radians(90)} 0"/>
                <geometry>
                    <cylinder radius="0.001" length="0.02"/>
                </geometry>
                <material name="red">
                    <color rgba="1.0 0.0 0.0 1.0"/>
                </material>
            </visual>
            
            <!-- Y軸（右方向）- 緑色 -->
            <visual name="y_axis">
                <origin xyz="0 0.01 0" rpy="${radians(90)} 0 0"/>
                <geometry>
                    <cylinder radius="0.001" length="0.02"/>
                </geometry>
                <material name="green">
                    <color rgba="0.0 1.0 0.0 1.0"/>
                </material>
            </visual>
            
            <!-- Z軸（上方向）- 青色 -->
            <visual name="z_axis">
                <origin xyz="0 0 0.01" rpy="0 0 0"/>
                <geometry>
                    <cylinder radius="0.001" length="0.02"/>
                </geometry>
                <material name="blue">
                    <color rgba="0.0 0.0 1.0 1.0"/>
                </material>
            </visual>
            
            <!-- 座標原点 - 白色 -->
            <visual name="origin">
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <sphere radius="0.003"/>
                </geometry>
                <material name="white">
                    <color rgba="1.0 1.0 1.0 1.0"/>
                </material>
            </visual>
        </link>
        
        <!--joint の定義-->
        <!-- base と motor を固定するジョイント -->
        <joint name="body_motor_fixedjoint_limb${limb_id}" type="fixed">
            <origin xyz="${(cylinder_radius)*cos(radians(arc))} ${(cylinder_radius)*sin(radians(arc))} ${-motor_height}" rpy="0 ${radians(180)} ${radians(270+arc)}"/>
            <parent link="body_link"/>
            <child link="motor${limb_id}"/>
        </joint>

        <!-- motor と leg_coxa　をジョイント-->
        <joint name = "limb${limb_id}_joint1" type = "continuous">
            <origin xyz="0 0 0.05" rpy="0 0 ${radians(180)}"/>
            <parent link="motor${limb_id}"/>
            <child link="limb${limb_id}_link2"/>
            <axis xyz="0.0 0.0 1.0"/>
        </joint>

        <!-- leg_coxa と leg_fumer　をジョイント-->
        <joint name="limb${limb_id}_joint2" type="continuous">
            <origin xyz="0.0 -0.0145 0" rpy="0 ${radians(90)} 0"/>
            <parent link="limb${limb_id}_link2"/>
            <child link="limb${limb_id}_link4"/>
            <axis xyz="0.0 -1.0 0.0"/>
        </joint>

        <!-- leg_fumer と leg_tibia　をジョイント-->
        <joint name="limb${limb_id}_joint3" type="continuous">
            <origin xyz="-0.105 0.0 0" rpy="0 0 0"/>
            <parent link="limb${limb_id}_link4"/>
            <child link="limb${limb_id}_link6"/>
            <axis xyz="0.0 1.0 0.0"/>
        </joint>     

        <!-- tibiaリンクと脚先を接続する固定ジョイント -->
        <joint name="limb${limb_id}_foot_joint" type="fixed">
            <!-- tibiaのSTLモデルの先端までの距離を設定 -->
            <origin xyz="-0.103 0.0205 -0.00205" rpy="${radians(-90)} 0 ${radians(-90)}"/>
            <parent link="limb${limb_id}_link6"/>
            <child link="limb${limb_id}_foot_tip"/>
        </joint>


        <!-- トランスミッション -->
    <transmission name="trans${limb_id}_1">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="limb${limb_id}_joint1"> 
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor${limb_id}_1">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="trans${limb_id}_2">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="limb${limb_id}_joint2"> 
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor${limb_id}_2">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="trans${limb_id}_3">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="limb${limb_id}_joint3"> 
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="motor${limb_id}_3">
        <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>



    </xacro:macro>
    
    <joint name = "body_joint" type="fixed">
        <parent link="base_link"/>
        <child  link="body_link"/>
    </joint>

    <link name="base_link"/> <!--baselink設定-->
    <link name="body_link"> <!--body設定-->
        <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.870"/>
        <inertia ixx="0.1" iyy="0.1" izz="0.1" ixy="0.0" iyz="0.0" ixz="0.0"/>
        </inertial>
        <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <mesh filename="package://dual_leg_controller/model/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="gray">
            <color rgba="0.7 0.7 0.7 1.0"/>
        </material>
        </visual>
        <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <mesh filename="package://dual_leg_controller/model/meshes/base_link.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        </collision>
    </link>

    <xacro:limb_macro limb_id="0" arc="0"/>
    <xacro:limb_macro limb_id="1" arc="60"/>
    <xacro:limb_macro limb_id="2" arc="120"/>
    <xacro:limb_macro limb_id="3" arc="180"/>
    <xacro:limb_macro limb_id="4" arc="240"/>
    <xacro:limb_macro limb_id="5" arc="300"/>


    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
        <robotNamespace>/multileg</robotNamespace>
        </plugin>
    </gazebo>

</robot>